jokangmin/Moivo_project

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/store/controller/StoreController.java, src/main/java/com/example/demo/store/repository/ProductRepository.java, src/main/java/com/example/demo/store/service/ProductService.java, src/main/java/com/example/demo/store/service/impl/ProductServiceImpl.java
//상품 리스트, 카테고리별 검색 or 키워드별 검색 후 페이징처리-11/25-tang
=> //상품 리스트, 카테고리별 검색 or 키워드별 검색 후 페이징처리-11/25-tang

src/main/java/com/example/demo/user/controller/WishController.java, src/main/java/com/example/demo/user/entity/UserWishEntity.java, src/main/java/com/example/demo/user/service/impl/WishServiceImpl.java, src/main/moivo_react/package-lock.json, src/main/moivo_react/package.json, src/main/moivo_react/yarn.lock
=> 찜 삭제 완성 - 24.11.26 - uj

src/main/java/com/example/demo/jwt/filter/JwtAuthenticationFilter.java, src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/service/UserService.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/assets/css/LoadingModal.module.css, src/main/moivo_react/src/assets/css/product_list.module.css, src/main/moivo_react/src/components/Banner/banner.jsx, src/main/moivo_react/src/containers/product/LoadingModal.jsx, src/main/moivo_react/src/containers/product/product_detail.jsx, src/main/moivo_react/src/containers/product/product_list.jsx, src/main/moivo_react/src/containers/user/user_login.jsx, src/main/moivo_react/src/contexts/AuthContext.jsx
=> 상품리스트 및 렌더링 에러 해결

src/main/java/com/example/demo/user/controller/CartController.java, src/main/java/com/example/demo/user/entity/Size.java, src/main/java/com/example/demo/user/entity/SizeConverter.java, src/main/java/com/example/demo/user/entity/UserCartEntity.java, src/main/java/com/example/demo/user/repository/UserCartRepository.java, src/main/java/com/example/demo/user/service/CartService.java, src/main/java/com/example/demo/user/service/impl/CartServiceImpl.java
DB에는 size 의 타입이 Tinyint로 되어있어서 숫자로 저장하는갑다 싶어서  숫자로 변경해서 저장하긴 함. 모든 기능 포스트맨 테스트 완
=> 11-26 카트상품 추가/출력/삭제기능 추가

src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/entity/UserEntity.java, src/main/java/com/example/demo/user/repository/UserRepository.java, src/main/java/com/example/demo/user/service/UserService.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/assets/css/LoadingModal.module.css, src/main/moivo_react/src/containers/product/LoadingModal.jsx, src/main/moivo_react/src/containers/product/product_detail.jsx, src/main/moivo_react/src/containers/product/product_list.jsx, src/main/moivo_react/src/contexts/AuthContext.jsx
토큰 갱신 로직(back) 수정 및  페이지 렌더링 수정 & 상품리스트 이미지 렌더링 수정 & 로딩 모달 수정
=> 토큰 갱신 로직(back) 수정 및  페이지 렌더링 수정 & 상품리스트 이미지 렌더링 수정 & 로딩 모달 수정_241127오전

src/main/java/com/example/demo/user/dto/UserCartDTO.java, src/main/java/com/example/demo/user/service/impl/CartServiceImpl.java
=> 11.27- 장바구니 출력- 가져오는 값 수정

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/user/controller/WishController.java, src/main/java/com/example/demo/user/repository/UserWishRepository.java, src/main/java/com/example/demo/user/service/impl/WishServiceImpl.java, src/main/moivo_react/src/containers/product/product_detail.jsx, src/main/moivo_react/src/containers/product/product_list.jsx
장바구니 상품 개수 렌더링
장바구니 화면 이동
위시리스트 상품 개수 렌더링
위시리스트 상품 추가
위시리스트 화면 이동
미완
* 장바구니 상품 추가 부분 흐름 고민 필요
=> 24.11.28 - 상품 목록 장바구니 & 위시 - uj

src/main/java/com/example/demo/store/controller/StoreController.java, src/main/java/com/example/demo/store/dto/ProductDTO.java, src/main/java/com/example/demo/store/dto/ProductStockDTO.java, src/main/java/com/example/demo/store/entity/ProductEntity.java, src/main/java/com/example/demo/store/entity/ReviewEntity.java, src/main/java/com/example/demo/store/service/ProductService.java, src/main/java/com/example/demo/store/service/impl/ProductServiceImpl.java, src/main/moivo_react/src/containers/product/product_detail.jsx, src/main/moivo_react/src/containers/product/product_list.jsx
상품 상세 정보(리뷰포함) 추출 수정 (front, back)
=> 24.11.29 - 상품 상세 정보(리뷰포함) 추출 수정 (front, back) - uj

src/main/java/com/example/demo/store/dto/ProductDTO.java, src/main/java/com/example/demo/store/entity/ProductEntity.java, src/main/moivo_react/src/containers/product/product_list.jsx, src/main/moivo_react/src/containers/test/upload.jsx
11.29 - 상품 성별 추가(back) & 페이지 이동 수정(front) - uj
=> 11.29 - 상품 성별 추가(back) & 페이지 이동 수정(front) - uj

src/main/java/com/example/demo/store/controller/AdminStoreController.java, src/main/java/com/example/demo/store/controller/StoreController.java, src/main/java/com/example/demo/store/entity/ProductEntity.java, src/main/java/com/example/demo/store/service/ProductService.java, src/main/java/com/example/demo/store/service/impl/ProductServiceImpl.java, src/main/moivo_react/src/containers/test/update.jsx, src/main/moivo_react/src/containers/test/upload.jsx
상품 성별 추가에 따른수정
상품 화면 및 DB 반영
1. 상품 업로드 기능 
: Front & Back 테스트 성공
2. 상품 수정 기능 및 상품 정보 출력 변수명 수정
: Front & Back 테스트 성공
상품 업로드 및 수정 화면
1. Back: 상품 성별에 대한 정보 출력
: 테스트 성공
2. Front: 상품 성별 드롭 다운 생성
: 테스트 성공
=> 24.11.29 - 상품 성별 추가에 따른 수정 - uj

build.gradle, src/main/java/com/example/demo/store/controller/StoreController.java, src/main/moivo_react/src/assets/css/product_detail.module.css, src/main/moivo_react/src/containers/product/product_detail.jsx, src/main/moivo_react/src/containers/product/product_list.jsx, src/main/moivo_react/src/contexts/AuthContext.jsx
=> 상품상세페이지 및 오류수정+test 머징

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/jwt/security/CustomUserDetails.java, src/main/java/com/example/demo/jwt/util/JwtUtil.java, src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/entity/UserEntity.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/containers/user/user_login.jsx, src/main/moivo_react/src/contexts/AuthContext.jsx, src/main/moivo_react/src/utils/apiClient.js
=> 로그인 문제 및 토큰 문제 해결

src/main/java/com/example/demo/payment/entity/PaymentEntity.java
=> 24.12.11 - 결제 테이블 구조 변경 - uj

src/main/java/com/example/demo/user/service/impl/CartServiceImpl.java
=> 장바구니 정상화_ 24.12.11 PM 14:50

src/main/java/com/example/demo/qna/repository/QuestionRepository.java
=> repository 에 트랜잭션 어노테이션 추가

src/main/moivo_react/src/containers/pay/payment.jsx
=> 결제페이지 쿠폰오류 해결

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/payment/entity/PaymentDetailEntity.java, src/main/java/com/example/demo/payment/entity/PaymentEntity.java, src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java, src/main/java/com/example/demo/qna/entity/QuestionEntity.java, src/main/java/com/example/demo/store/service/impl/ProductServiceImpl.java, src/main/java/com/example/demo/user/entity/CartEntity.java
24.12.12 - payment 결제 기능 완성 - uj
- 결제 정보 저장: Payment Table, PaymentDetail Table
- 상품 재고 수정: ProductStock Table
- 장바구니 상품 제거 수정: UserCart Table
24.12.13 - payment 시간 수정
=> 24.12.12 - payment 결제 기능 완성 - uj

src/main/java/com/example/demo/payment/controller/AdminPaymentController.java, src/main/java/com/example/demo/payment/controller/PaymentController.java, src/main/java/com/example/demo/payment/repository/PaymentRepository.java, src/main/java/com/example/demo/payment/service/AdminPaymentService.java, src/main/java/com/example/demo/payment/service/impl/AdminPaymentServiceImpl.java
24.12.13 - 관리자 판매현황 조회 백 완성 - uj
- AdminPaymentController.java
- AdminPaymentServiceImpl.java
=> 24.12.13 - 관리자 판매현황 조회 백 완성 - uj

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/qna/controller/QuestionController.java, src/main/java/com/example/demo/qna/entity/QuestionEntity.java, src/main/java/com/example/demo/qna/repository/QuestionRepository.java, src/main/java/com/example/demo/qna/service/QuestionService.java, src/main/java/com/example/demo/qna/service/impl/QuestionServiceImpl.java
test 브랜치 합병, 문의 로직수정 및 QuestionEntity categoryEntity에 @JsonIgnore 추가 12/13 15:03 tang
=> test 브랜치 합병, 문의 로직수정 및 QuestionEntity categoryEntity에 @JsonIgnore 추가 12/13 15:03 tang

src/main/java/com/example/demo/payment/controller/PaymentController.java, src/main/java/com/example/demo/payment/entity/PaymentEntity.java, src/main/moivo_react/src/containers/pay/payment-success.jsx, src/main/moivo_react/src/containers/pay/payment.jsx
24.12.17 - uj
- 결제 성공 시, 서버 측에 요청하는거 수정 (재영이가 작성한 대로) : payment-success.jsx
- 쿠폰 적용한 할인 가격 전송
=> 24.12.17 - 결제 성공 시, 서버 측에 요청하는거 수정 & 쿠폰 적용한 할인 가격 전송 - uj

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/payment/dto/PaymentDetailDTO.java, src/main/java/com/example/demo/payment/entity/PaymentDetailEntity.java, src/main/java/com/example/demo/store/controller/ReviewController.java, src/main/java/com/example/demo/store/dto/ReviewDTO.java, src/main/java/com/example/demo/store/entity/ReviewEntity.java, src/main/java/com/example/demo/store/service/ReviewService.java, src/main/java/com/example/demo/store/service/impl/ReviewServiceImpl.java, src/main/java/com/example/demo/user/controller/CartController.java, src/main/java/com/example/demo/user/service/CartService.java, src/main/java/com/example/demo/user/service/impl/CartServiceImpl.java
24.12.17 - uj
- 장바구니 상품 추가 오류 수정
- 리뷰 작성 여부 추가
- 리뷰 테이블이랑 결제 상세 테이블 조인
=> 24.12.17 - 리뷰 작성 여부 추가 & 리뷰 테이블이랑 결제 상세 테이블 조인  - uj

src/main/java/com/example/demo/store/controller/ReviewController.java, src/main/moivo_react/src/App.jsx, src/main/moivo_react/src/assets/css/ReviewWrite.module.css, src/main/moivo_react/src/containers/mypage/mypage_order.jsx, src/main/moivo_react/src/containers/review/review_write.jsx
[리뷰작성페이지/ api 연동 틀 24.12.17 17:55]
=> 리뷰작성페이지/ api 연동 틀 24.12.17 17:55_성찬

src/main/moivo_react/src/assets/css/ReviewWrite.module.css, src/main/moivo_react/src/containers/review/review_write.jsx
=> 리뷰 작성 페이지 수정 ! 12.17 18:09_성찬

src/main/java/com/example/demo/qna/controller/QuestionController.java, src/main/java/com/example/demo/qna/dto/QuestionDTO.java, src/main/java/com/example/demo/qna/repository/QuestionRepository.java, src/main/java/com/example/demo/qna/service/impl/QuestionServiceImpl.java, src/main/resources/application.yml
12/17 18:30 문의리스트 제목별, 카테고리별 검색 추가(한글검색은 2번해야 되는 오류.. 아직 해결중)
=> 12/17 18:30 문의리스트 제목별, 카테고리별 검색 추가(한글검색은 2번해야 되는 오류.. 아직 해결중)

src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java
=> 회원정보 수정(생일) 완료

src/main/java/com/example/demo/user/controller/CartController.java, src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/service/CartService.java, src/main/java/com/example/demo/user/service/impl/CartServiceImpl.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/containers/cart/cart.jsx
=> 24.12.18 - 장바구니 삭제 오류 수정 - uj

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/user/service/KakaoService.java, src/main/java/com/example/demo/user/service/impl/KakaoServiceImpl.java, src/main/java/com/example/demo/user/service/impl/SocialServiceImpl.java
24.12.18 - 카카오 소셜 로그인 오류 수정 - uj
=> 24.12.18 - 카카오 소셜 로그인 오류 수정 - uj

src/main/java/com/example/demo/store/controller/ReviewController.java, src/main/java/com/example/demo/store/controller/StoreController.java, src/main/java/com/example/demo/store/repository/ReviewRepository.java, src/main/java/com/example/demo/store/service/ReviewService.java, src/main/java/com/example/demo/store/service/impl/ReviewServiceImpl.java, src/main/java/com/example/demo/user/controller/UserController.java, src/main/moivo_react/src/App.jsx, src/main/moivo_react/src/assets/css/ReviewWrite.module.css, src/main/moivo_react/src/assets/css/product_detail.module.css, src/main/moivo_react/src/components/Banner/banner.jsx, src/main/moivo_react/src/containers/admin/admins_qnaboard.jsx, src/main/moivo_react/src/containers/product/product_detail.jsx, src/main/moivo_react/src/containers/review/review_write.jsx
리뷰작성 페이지 반응형 미디어쿼리 추가 및 디자인수정_12.18 12:55 _성찬
리뷰  전체조회 페이지 필요 의문?
리뷰 어떻게 수정/삭제 ?
=> 리뷰작성 페이지 반응형 미디어쿼리 추가 및 디자인수정_12.18 12:55 _성찬

src/main/java/com/example/demo/qna/repository/QuestionRepository.java, src/main/java/com/example/demo/qna/service/impl/QuestionServiceImpl.java
=> JPQL->JPA 수정

src/main/java/com/example/demo/qna/repository/QuestionRepository.java, src/main/java/com/example/demo/qna/service/impl/QuestionServiceImpl.java
=> 문의 레포지토리 2차 수정 12/18 21:00 

src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/containers/qna/qna_boardlist.jsx
회원가입 수정 + test 브랜치 12/19 장훈 (12:41)
=> 회원가입 수정 + test 브랜치 12/19 장훈 (12:41)

src/main/java/com/example/demo/qna/controller/QuestionController.java, src/main/java/com/example/demo/qna/service/impl/QuestionServiceImpl.java
문의 수정시 카테고리변경 추가 및 코드 리팩토링 -12/19 15:45
=> 문의 수정시 카테고리변경 추가 및 코드 리팩토링 -12/19 15:45

src/main/java/com/example/demo/coupon/dto/CouponDTO.java, src/main/java/com/example/demo/coupon/dto/UserCouponDTO.java, src/main/java/com/example/demo/coupon/entity/UserCouponEntity.java, src/main/java/com/example/demo/coupon/service/impl/UserCouponServiceImpl.java, src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java, src/main/java/com/example/demo/store/controller/AdminStoreController.java, src/main/java/com/example/demo/store/service/AdminStoreService.java, src/main/java/com/example/demo/store/service/ProductService.java, src/main/java/com/example/demo/store/service/ReviewService.java, src/main/java/com/example/demo/store/service/impl/AdminStoreServiceImpl.java, src/main/java/com/example/demo/store/service/impl/ProductServiceImpl.java, src/main/java/com/example/demo/user/dto/UserDTO.java, src/main/java/com/example/demo/user/service/impl/MypageServiceImpl.java, src/main/moivo_react/src/containers/mypage/mypage_main.jsx
24.12.19 - 쿠폰 관련 오류 수정 완료 - uj
=> 24.12.19 - 쿠폰 관련 오류 수정 완료 - uj

src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/repository/UserRepository.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java
회원가입시 ID 중복 예외처리 12/19 17:16 tang
=> 회원가입시 ID 중복 예외처리 12/19 17:16 tang

src/main/java/com/example/demo/coupon/dto/UserCouponDTO.java, src/main/java/com/example/demo/coupon/repository/UserCouponRepository.java, src/main/java/com/example/demo/coupon/service/impl/UserCouponScheduler.java, src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java, src/main/java/com/example/demo/qna/controller/QuestionController.java, src/main/moivo_react/src/assets/css/Mypage.module.css, src/main/moivo_react/src/assets/css/admins_dashboard.module.css, src/main/moivo_react/src/containers/admin/admin_productList.jsx, src/main/moivo_react/src/containers/admin/admins_dashboard.jsx, src/main/moivo_react/src/containers/admin/admins_productupdate.jsx, src/main/moivo_react/src/containers/mypage/mypage_main.jsx, src/main/moivo_react/src/containers/pay/payment.jsx, src/main/moivo_react/src/containers/qna/qna_boardlist.jsx
결제페이지 - 쿠폰사용할 때 최소금액 설정
마이페이지 메인 - 쿠폰 유효기간 확인 가능
=> 쿠폰 최소금액 &쿠폰 유효기간 설정 - sumin (12.19 18:25)

src/main/java/com/example/demo/coupon/service/impl/UserCouponServiceImpl.java, src/main/java/com/example/demo/payment/entity/PaymentDetailEntity.java, src/main/java/com/example/demo/store/controller/ReviewController.java, src/main/java/com/example/demo/store/entity/ReviewEntity.java, src/main/java/com/example/demo/store/service/impl/ReviewServiceImpl.java, src/main/java/com/example/demo/user/service/impl/MypageServiceImpl.java
=> 24.12.19 - 리뷰 삭제 - uj

src/main/moivo_react/src/assets/css/qna_faqboard.module.css, src/main/moivo_react/src/containers/qna/qna_board.jsx, src/main/moivo_react/src/containers/qna/qna_faqboard.jsx
FAQ 페이징처리 및 반응형 디자인 추가 12.20 10:37_성찬
=> FAQ 페이징처리 및 반응형 디자인 추가 12.20 10:37_성찬

src/main/moivo_react/src/assets/css/Mypage_profile.module.css, src/main/moivo_react/src/assets/css/user_login.module.css, src/main/moivo_react/src/assets/css/user_sigup.module.css, src/main/moivo_react/src/containers/qna/qna_board.jsx
화면 input css 수정 + test브랜치 12/20 장훈 (11:08)
=> 화면 input css 수정 + test브랜치 12/20 장훈 (11:08)

src/main/moivo_react/src/containers/product/product_detail.jsx
[상품상세페이지 위시로직수정, 바로구매하기 버튼 로직수정 12.20 11:11]
=> [상품상세페이지 위시로직수정, 바로구매하기 버튼 로직수정 12.20 11:11]_성찬

src/main/java/com/example/demo/configuration/SecurityConfig.java, src/main/java/com/example/demo/qna/controller/QuestionController.java, src/main/java/com/example/demo/qna/dto/QuestionDTO.java, src/main/java/com/example/demo/qna/service/impl/AdminManagementServiceImpl.java, src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/service/UserService.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/containers/qna/qna_boardlist.jsx, src/main/moivo_react/src/containers/user/user_signup.jsx
회원가입시 ID 중복 예외처리 수정(UserController
join 에서 했던걸 idCheck로 교체 - 완료
회원가입시 ID focus out시 (사용중인 ID, 가입 가능한 아이디 적용) - 완료
글 리스트 작성자 name으로 변경 - 완료
=> 회원가입시 ID 중복 예외처리 수정(UserController join 에서 했던걸 idCheck로 교체 - 완료 회원가입시 ID focus out시 (사용중인 ID, 가입 가능한 아이디 적용) - 완료 글 리스트 작성자 name으로 변경 - 완료 12/20 12:18

build.gradle, src/main/java/com/example/demo/coupon/service/impl/UserCouponServiceImpl.java, src/main/java/com/example/demo/payment/service/impl/PaymentScheduler.java, src/main/java/com/example/demo/payment/service/impl/PaymentServiceImpl.java, src/main/java/com/example/demo/user/service/impl/MypageServiceImpl.java, src/main/moivo_react/src/containers/admin/admin_productList.jsx
구매확정이 되면 등급 업데이트 + 쿠폰 발급
등급, 쿠폰쪽 오류 해결
쿠폰 유효기간 수정
- sumin (24.12.20 12:33)
=> 등급&쿠폰 코드 수정- sumin (24.12.20 12:33)

src/main/java/com/example/demo/coupon/repository/UserCouponRepository.java, src/main/java/com/example/demo/payment/repository/PaymentDetailRepository.java, src/main/java/com/example/demo/payment/repository/PaymentRepository.java, src/main/java/com/example/demo/qna/repository/QuestionRepository.java, src/main/java/com/example/demo/user/repository/UserCartRepository.java, src/main/java/com/example/demo/user/repository/UserWishRepository.java, src/main/java/com/example/demo/user/repository/WishRepository.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/containers/mypage/mypage_profile.jsx
마이페이지 프로필 오류 해결 - sumin (12.20 15:40)
=> 마이페이지 프로필 오류 해결 - sumin (12.20 15:40)

src/main/java/com/example/demo/payment/entity/PaymentEntity.java, src/main/java/com/example/demo/payment/repository/PaymentRepository.java, src/main/java/com/example/demo/qna/entity/QuestionEntity.java, src/main/java/com/example/demo/qna/repository/QuestionRepository.java, src/main/java/com/example/demo/qna/repository/QuestionRepositoryCustom.java, src/main/java/com/example/demo/qna/repository/QuestionRepositoryCustomImpl.java, src/main/java/com/example/demo/store/entity/ReviewEntity.java, src/main/java/com/example/demo/store/repository/ReviewRepository.java, src/main/java/com/example/demo/store/repository/ReviewRepositoryCustom.java, src/main/java/com/example/demo/store/repository/ReviewRepositoryCustomImpl.java, src/main/java/com/example/demo/user/controller/UserController.java, src/main/java/com/example/demo/user/repository/UserCartRepository.java, src/main/java/com/example/demo/user/repository/UserWishRepository.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/containers/mypage/mypage_profile.jsx
=> 회원탈퇴 성공 - sumin (12.20 17:52)

src/main/java/com/example/demo/qna/service/impl/QuestionServiceImpl.java, src/main/java/com/example/demo/user/controller/MypageController.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/src/assets/css/Mypage_board.module.css, src/main/moivo_react/src/containers/mypage/mypage_board.jsx
마이페이지 내 문의 수정, 삭제 마이페이지 수정 삭제 추가하면서 작성한 날짜 위치 변경 12/20 18:00 tang
=> 마이페이지 내 문의 수정, 삭제 마이페이지 수정 삭제 추가하면서 작성한 날짜 위치 변경 12/20 18:00 tang

src/main/moivo_react/src/assets/css/user_login.module.css, src/main/moivo_react/src/containers/user/user_login.jsx
login 버튼 css, 반응형 수정 12/20 장훈 (18:04)
=> login 버튼 css, 반응형 수정 12/20 장훈 (18:04)

src/main/java/com/example/demo/store/controller/AdminStoreController.java, src/main/java/com/example/demo/store/dto/ProductCategoryDTO.java, src/main/java/com/example/demo/store/dto/ProductDTO.java, src/main/java/com/example/demo/store/entity/ProductCategoryEntity.java, src/main/java/com/example/demo/store/repository/ProductCategoryRepository.java, src/main/java/com/example/demo/store/repository/ProductRepository.java, src/main/java/com/example/demo/store/service/AdminStoreService.java, src/main/java/com/example/demo/store/service/ProductService.java, src/main/java/com/example/demo/store/service/impl/AdminStoreServiceImpl.java, src/main/java/com/example/demo/store/service/impl/ProductServiceImpl.java, src/main/moivo_react/scripts/path.js
24.12.23 - 상품 카테고리DB 변경에 따른 수정 - uj
=> 24.12.23 - 상품 카테고리DB 변경에 따른 수정 - uj

src/main/moivo_react/scripts/path.js
=> path 경로 수정

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중2

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중3

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중4

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중5

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중6

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중7

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중8

src/main/moivo_react/src/assets/css/Mypage_profile.module.css
=> profile css 수정 중9

src/main/moivo_react/src/assets/css/user_sigup.module.css
=> 회원가입&프로필 성별 css 수정 완

src/main/moivo_react/src/containers/user/user_signup.jsx, src/main/moivo_react/src/contexts/user/User_SignUpContext.jsx
Sign Up 예외처리 수정 12/26 장훈 (15:32)
=> Sign Up 예외처리 수정 12/26 장훈 (15:32)

src/main/moivo_react/src/containers/admin/admins_productadd.jsx, src/main/moivo_react/src/containers/admin/admins_productupdate.jsx
상품 관리 세부 카테고리 완료 12/27 장훈 (01:10)
=> 상품 관리 세부 카테고리 완료 12/27 장훈 (01:10)

src/main/java/com/example/demo/user/controller/SocialController.java, src/main/java/com/example/demo/user/service/impl/KakaoServiceImpl.java, src/main/java/com/example/demo/user/service/impl/SocialServiceImpl.java, src/main/java/com/example/demo/user/service/impl/UserServiceImpl.java, src/main/moivo_react/scripts/path.js, src/main/moivo_react/src/App.jsx, src/main/moivo_react/src/components/kakao/KakaoCallback.jsx, src/main/moivo_react/vite.config.js, src/main/resources/application.yml
24.12.27
[ 카카오 로그인 오류 수정 완료 ]
- 확장자 추가
- 상대 -> 절대 경로로 변경 
: vite.config.js 파일
=> 24.12.27 - 카카오로그인 오류 수정 완료 - uj

src/main/java/com/example/demo/payment/dto/PaymentDetailDTO.java, src/main/java/com/example/demo/payment/service/impl/PaymentScheduler.java, src/main/java/com/example/demo/user/service/impl/MypageServiceImpl.java
스케줄러 데드락 해결 - sumin(12.27 12:51)
=> 스케줄러 데드락 해결 - sumin(12.27 12:51)

src/main/moivo_react/scripts/path.js, src/main/moivo_react/src/components/Banner/banner.jsx, src/main/moivo_react/src/components/admin_sidebar/admins_side.jsx, src/main/moivo_react/src/contexts/user/User_LoginContext.jsx
hoon브랜치 작업물 + path로컬 수정 12/27 장훈 (13:01)
=> hoon브랜치 작업물 + path로컬 수정 12/27 장훈 (13:01)

src/main/moivo_react/scripts/path.js, src/main/moivo_react/src/assets/css/product_detail.module.css, src/main/moivo_react/src/contexts/productCon/ProListContext.jsx
상품상세페이지의 상세정보 이미지 크기 수정_12.27 13:08_성찬
=> 상품상세페이지의 상세정보 이미지 크기 수정_12.27 13:08_성찬

src/main/moivo_react/src/assets/css/product_board.module.css, src/main/moivo_react/src/containers/product/product_board.jsx
moivo-version3.0.2
today style 반응형 및 클릭 이동 수정 - 12/27 15:04 강민
=> today style 반응형 및 클릭 이동 수정 - 12/27 15:04 강민

src/main/java/com/example/demo/payment/dto/PaymentDetailDTO.java, src/main/moivo_react/scripts/path.js, src/main/moivo_react/src/assets/css/Mypage_orderDetails.module.css, src/main/moivo_react/src/assets/css/Mypage_profile.module.css, src/main/moivo_react/src/containers/cart/cart.jsx, src/main/moivo_react/src/containers/mypage/mypage_main.jsx, src/main/moivo_react/src/containers/mypage/mypage_orderDetails.jsx, src/main/moivo_react/src/containers/mypage/mypage_profile.jsx, src/main/moivo_react/src/contexts/mypageCon/MypageOrderDetailContext.jsx, src/main/moivo_react/src/contexts/mypageCon/MypageProfileContext.jsx
mypage orderdetail 할인금액 출력 - sumin(12.27 15:52)
=> mypage orderdetail 할인금액 출력 - sumin(12.27 15:52)

src/main/moivo_react/src/assets/css/Cart.module.css, src/main/moivo_react/src/containers/cart/cart.jsx, src/main/moivo_react/src/contexts/cartCon/CartContext.jsx, src/main/moivo_react/src/contexts/mypageCon/MypageContext.jsx
장바구니 전체선택 버튼 생성 - sumin (12.27 16:38)
=> 장바구니 전체선택 버튼 생성 - sumin (12.27 16:38)

src/main/moivo_react/scripts/path.js, src/main/resources/application-mysql.properties, src/main/resources/application.yml
24.12.27 - uj
- 배포 테스트 DB 정보 제거 1~3
: application-mysql.properties 리눅스 서버에만 존재 
로컬에서 실행시키기 위해서는 src/main/resources/application-mysql.properties 에 위치하여야 함.
=> 24.12.27 - [배포 테스트 DB 정보 제거 1~3] - uj

src/main/moivo_react/src/assets/css/product_detail.module.css, src/main/moivo_react/src/contexts/productCon/ProListContext.jsx, src/main/resources/application.yml
상품목록 의존성 배열 추가 + 상세페이지 일부 반응형 css 수정 + yml 적용_성찬_24.12.30 16:00
=> 상품목록 의존성 배열 추가 + 상세페이지 일부 반응형 css 수정 + yml 적용_성찬_24.12.30 16:00

src/main/java/com/example/demo/user/entity/UserEntity.java, src/main/moivo_react/src/contexts/productCon/ProListContext.jsx
25.01.02 - 상품 목록 API 2번 호출 오류 해결 & Grade에 ADMIN 추가 - uj
=> 25.01.02 - 상품 목록 API 2번 호출 오류 해결 & Grade에 ADMIN 추가 - uj

src/main/moivo_react/scripts/path.js
=> moivo 5.0.0 - uj

src/main/moivo_react/src/assets/css/product_board.module.css
=> 대시보드쪽 css 수정_25.01.02_yjy

src/main/moivo_react/scripts/path.js, src/main/moivo_react/src/components/Banner/banner.jsx, src/main/moivo_react/src/contexts/mypageCon/MypageProfileContext.jsx
=> 정보수정 정규화 및 포커스_25.01.02_yjy
